env:
  global:
    - MAVEN_OPTS=-Dmaven.repo.local=.m2/repository
    - MQTT_WEBSOCKET_VERSION=1.0.1
    
cache:
  directories:
  - .jmeter
  - .m2

language: java

jdk:
- oraclejdk8

before_install: 
  - sudo apt-get -y update
  - sudo apt-get -y install python default-jre-headless python-tk python-pip python-dev libxml2-dev libxslt-dev zlib1g-dev net-tools
  - sudo pip install bzt==1.11.0
  - chmod -R +x ./.travis
  - "sh ./.travis/install-maven-dependency.sh https://github.com/inventit/mqtt-websocket-java/releases/download/$MQTT_WEBSOCKET_VERSION/mqtt-websocket-java-$MQTT_WEBSOCKET_VERSION.jar io.inventit.dev mqtt-websocket-java $MQTT_WEBSOCKET_VERSION"

script:
  - "mvn -DskipTests=true clean install --batch-mode"
  - "mvn -Djava.awt.headless=true -Dmaven.test.redirectTestOutputToFile=true -Dcobertura.report.format=xml --fail-at-end --batch-mode cobertura:cobertura test"

after_success:
  - bash <(curl -s https://codecov.io/bash)
